language: go
go:
- '1.11'
services:
- docker
sudo: required
env:
  matrix:
  - SSL_MODE_DISABLE=true
  global:
  # this decodes to env variable SENDGRID_API_KEY
  - secure: ffB0PFzAvfnEIPAKKn+aQesTpikncfAlZX6XpV+NfF/pP/1ll6fyTW7qa6V2q8v2cNu16cYGn80PvcP4RY42Vno7ATrz7FVAJx7R/WRZRBXJB0+Bwlp8qp+xLRKziwBleyXlQ6OSz5CMZOUC3IrlPR8n7QbvoY/p1YPkPfo2WxcWuppdK5kcaqa1DfNS4ZjOvsaeTWZBKOJoLHy+8g+KuK79pkr+aTXOLc2r2M31c2KGx4W69qmeUrJx8uchwDhTxz1xDitys/fJOoDVxmrCOSBmEPxauo5Jj58qiM2hslaEdqvR3AjJoun8K/K6iy5FtBJ10gBXIT057Gj92LxVfIx08pVDkq0FgtO3t17bKi5/n787uVz0rZu1WEnlgRhx9Pcp9fQnpBCXWRy9X2EmVyN3caXE1MWupkmHoF7pgp8yn3iAdm9dKb2C17D07kjp9BmKopza0Ro6GfLkcpmpBVmNx2+QpSzBaQfMM96oF2sHbqZ5VdE7UtIjm9Osv8WFpT13m1mk6RUSOb4girJ3MmcxA5g4YFpMb73BCCC0twuTWoRYJXSNvwmbYtFiACM3Z2kBKV8rlbdwsqPl1ISZThUrhkmlnU0eY121Buv9Oo+1tmW5ZxoOMTk9pt+0TGswj3jv405T31ssBuIfK6A0IHXnBnSfz8QC6e4JjYUHLCg=

install:
- go get -u golang.org/x/lint/golint
- git submodule update --init

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
- make testenv

script:
- diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
- diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
- go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- make release-cli

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Xv0Zq+E638TZf0c3/tTUk/iizQ92hhW02cWUSnmGlBpWR8O5qvfcrgBYpohMIyFn42WEa/vJWT51aIfoZX779Xj41LodXx1QqnI/kQFHlVETeGXhsBbw8OsVAgKNtUII5XxrdyTe8h1JrFqCbynUgsBQK6t+ibTKYL4MTXwoJ3snGHiA7u0QVGWX4o3Q4axWqwJDVFFiSC1ekfRULgoINouAJcLVXvVp3VJOf7R8TZM9HgeSmiq+Vjm9eZ4hh3A3f312dO6T+duFhCBzU3aqktJYzJPxtQ5IcYc0Yr4rI1s2CKReT9qRdWjfSyQieCEDSS8miW3zChbdFGl1ntSJypOCh923jeAOMWDrichDB5icQNL/svpE128TxwEJt70MAK/0AFF/1t676kuEskEbTwFGBTmKW8y1F2AejwsnkxfUpKrzabkVDksLt0kqXBEPkrdCeCQ+/WvjPIHarO+zi6J7Qn38PaZBR7P/ssghvDjusZA1zm2ZoffvB5O0KGQ64fivcCeCuONGlouFXX/77NnmvYY8ua6QKLIkq3QnwOeGZNeCFWAQWd9rn2KM64K6AvoyIHRuBFB+FtIrZKHj9N2iVytnnqOvfnfySQg6ieiRuKJMjDnLQDoQdhuW0KJmaxOCMpNiE95Pj1GsepfMZe04fXLSO4srIfnedRFk7/Q=
  file_glob: true
  file: release/temporal-*
  on:
    tags: true
    repo: RTradeLtd/Temporal

notifications:
  email: false
