language: go
go:
- '1.14.1'
services:
- docker
sudo: required
env:
  matrix:
    - SSL_MODE_DISABLE=true
  global:
    - GO111MODULE=on
    - RECAPTCHA_KEY=cantbeblankortestsfail
    # decodes into SENGRID_API_KEY environment variable
    - secure: GXKJ+1Wa+pqUm1PKHJMbDrejSfIsqhsZ6l88i0paTvVou9T/mv03mx9hzrSLsYXFFVjinfbKysxMtEorTFDl0YBSNxuPc7eaiJinnoptubBh++bvEzF/A8wmWHgIBxroFIrK4SNsnreCXPqT1YBQZWi3JenMkzS68j1oa/uPa5ODZ3rjx1Wmu6hSANSZPqzOoGO6lnRP8G30oiFzbawEnB/52iBcHhPtffUihLFnn3k1wXyL8fpi4JYuyNQe84Br+w91KSS2nMmG+RVvJWumHNGXFyjEVv0n7HbirjCBI1iZo50bTdFtujkGSOCoHqM1hwa2yLWISipkb19Ls4eeWcWZBFpcdBhIIeHEmz9iCXxn0ksIGzuw00Xof/HTcWUpnzzQFq4E8iVE4tmMrFbYEcD5vcGB3S7bURjTD38uZ3/7I4Oyuo33/WQGdDNIzugU/dycGkSNzwTeIB3yJfpr/wbC6lU5RnADh5Ej5hGreAfkng/iuC9T36Fnn9u4fTocj++smOxZSjbbKsyekNNdadYmU0sfd6Ka9mFcv8H6sDs7zwqyZLTDu6P57CN5VFz4Yjc1emupFX5NFWor5jull9cr+ilOmfnBSCQPV0ArKrpKjrL9K9NJAhRKOqxmpLKx3pozGnrQMFKM0xsSuTcOCdyTdZF8JEQESeENHzwyoB4=
install:
- go get honnef.co/go/tools/cmd/staticcheck
- go get -u golang.org/x/lint/golint
- git submodule update --init
- go mod download
- ( cd testenv ; go mod download )

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
- make testenv
- make run-swarm

script:
- diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
- diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
- go test -short -failfast -coverprofile=coverage.txt ./...
# - go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- make release-cli

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Gy80n9OjP4xQW6X2ybn402ldU1lbV855ylqgZApIkEZkSclBrM/qFvOZ6WjbS6P0gqUkEJ58tXpMgktPAPcgCxB/28c78xFuv/ABlirdXN8gL1Wwfq3twMxlHphHwzp8OGLKRmzbiku3dTDXWgtQBvlwMd8lStjrjIZmB4iJW2PVmzSz2TZYRjpd82ZOsJlk6tZ0jrKrfr85nd1MQ+8FkRHkA6Os/4353sI0yMx8W2Q1TggfM7PkgyVdRZOMijaCAq1c9VdlIXGz11c39HDw0bgq6gxLCrk/B3OUzFryr0NgfsCDTGqzdteJ+ndIqF+PtVlqfb8ZEJa8MrBOynfm5R+mVrQdMaiErYERQfULLxXtqbhGY4AGSBWH6nrXLdYqW3AFX8fG8hEBgE5Ls7N7se6yCBjG9qMZ9KUu9ks9RKhNibAxw8w9dfVvWhx2yqjGn4CZV6/zrHUGJxCgjHHEjp/1ksw5QAtZ7M+iNjW17seJXDXzB3pNhJ6N1TzZtShVR7Zg6YFN6Dx1S/DhA/YIaIKOHGvroJLNCF/jslqQ+Nluu14//SlHdCnOScQ5GnmetjLFOiTKd6V4mIX99a2tFCxJc8Jti1rqVZjD/OK13np/tOCk+7JezoCulJXklN/JPIpbIFPLyfmEDu/zSopucxLTip4WskqCv8UNc9eYIbY=
  file_glob: true
  file: release/temporal-*
  on:
    tags: true
    repo: RTradeLtd/Temporal

notifications:
  email: false

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build