language: go
go: 
        - "1.10"
services:
        - postgresql

before_script:
        - psql -c 'create database temporal;' -U postgres
        - scripts/travis_build.sh
addons:
    apt:
       update: true
dist: xenial
sudo: required