language: go
go:
- '1.11'
services:
- docker
sudo: required
env:
  matrix:
    - SSL_MODE_DISABLE=true
  global:
    # decodes into SENGRID_API_KEY environment variable
    - secure: GXKJ+1Wa+pqUm1PKHJMbDrejSfIsqhsZ6l88i0paTvVou9T/mv03mx9hzrSLsYXFFVjinfbKysxMtEorTFDl0YBSNxuPc7eaiJinnoptubBh++bvEzF/A8wmWHgIBxroFIrK4SNsnreCXPqT1YBQZWi3JenMkzS68j1oa/uPa5ODZ3rjx1Wmu6hSANSZPqzOoGO6lnRP8G30oiFzbawEnB/52iBcHhPtffUihLFnn3k1wXyL8fpi4JYuyNQe84Br+w91KSS2nMmG+RVvJWumHNGXFyjEVv0n7HbirjCBI1iZo50bTdFtujkGSOCoHqM1hwa2yLWISipkb19Ls4eeWcWZBFpcdBhIIeHEmz9iCXxn0ksIGzuw00Xof/HTcWUpnzzQFq4E8iVE4tmMrFbYEcD5vcGB3S7bURjTD38uZ3/7I4Oyuo33/WQGdDNIzugU/dycGkSNzwTeIB3yJfpr/wbC6lU5RnADh5Ej5hGreAfkng/iuC9T36Fnn9u4fTocj++smOxZSjbbKsyekNNdadYmU0sfd6Ka9mFcv8H6sDs7zwqyZLTDu6P57CN5VFz4Yjc1emupFX5NFWor5jull9cr+ilOmfnBSCQPV0ArKrpKjrL9K9NJAhRKOqxmpLKx3pozGnrQMFKM0xsSuTcOCdyTdZF8JEQESeENHzwyoB4=

install:
- go get -u golang.org/x/lint/golint
- git submodule update --init

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
- make testenv

script:
- diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
- diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
- go test -v -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- make release-cli

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: iYuxXhs8KXD+lqE9wVDoch+w3V+Gg3DI9tL5aVPGjegbJVgtVqujv2SHDzokmnnaWuW6a/4RLFhxlFDuAmU9pAd6wUxLEU5VZKxt9y8tUlVoq6VdlmqvPl7kJZ5Cxy5RCbqQFdIcIa40rbNmbdsasyqs7PU8t6G7P5Q/twg6CEiFynxmZ91ZbeGKl7WOzICOGqyxj/9R4Ps1qNmfpdSBpjTfMaiRbtHAZEXoL41WlbrkPZCMfHcO762YBlFZX4kenGN4u60yg6hPrDI7lyBHWJ6sLLwU4Jk8fbFUB5x678WcIFfxr1Djd1f/utke2wS+cn0gqjJUkW5mbpF4CYM4K9fJMvtBoszas3Gt+jvyFR46jk0zmfthlmk557Q9J76E0Z/1NSgl2mlq7Ji8gsp56TvRxmETgNPmbMKq542OPuOt51Bik94yPiCjTxe/m4UPxiF1xzfU2lmE04xQFE28ndELEUcpwj/LFuDPdJIGWKkc+k+ukfG/TwVL3Gelg/3SDSUEzwnoJnX9Wkd3ygAkYupfRXclB57J+UaNOWu1I/k3XcaNqxZm201OnK1FWNzz+QnNdeLPewdxdGNyLZ61QdqCEQfGZCWlPcp9Tkb0e//4vdARwLX4ym8Al5ynnlojCs+KK42KywXa01Q7avPZhPAS/TycflycBcxa7fo1dPY=
  file_glob: true
  file: release/temporal-*
  on:
    tags: true
    repo: RTradeLtd/Temporal

notifications:
  email: false
