language: go
go:
- '1.11'
services:
- docker
sudo: required
env:
  matrix:
    - SSL_MODE_DISABLE=true
  global:
    # decodes into SENGRID_API_KEY environment variable
    - secure: GXKJ+1Wa+pqUm1PKHJMbDrejSfIsqhsZ6l88i0paTvVou9T/mv03mx9hzrSLsYXFFVjinfbKysxMtEorTFDl0YBSNxuPc7eaiJinnoptubBh++bvEzF/A8wmWHgIBxroFIrK4SNsnreCXPqT1YBQZWi3JenMkzS68j1oa/uPa5ODZ3rjx1Wmu6hSANSZPqzOoGO6lnRP8G30oiFzbawEnB/52iBcHhPtffUihLFnn3k1wXyL8fpi4JYuyNQe84Br+w91KSS2nMmG+RVvJWumHNGXFyjEVv0n7HbirjCBI1iZo50bTdFtujkGSOCoHqM1hwa2yLWISipkb19Ls4eeWcWZBFpcdBhIIeHEmz9iCXxn0ksIGzuw00Xof/HTcWUpnzzQFq4E8iVE4tmMrFbYEcD5vcGB3S7bURjTD38uZ3/7I4Oyuo33/WQGdDNIzugU/dycGkSNzwTeIB3yJfpr/wbC6lU5RnADh5Ej5hGreAfkng/iuC9T36Fnn9u4fTocj++smOxZSjbbKsyekNNdadYmU0sfd6Ka9mFcv8H6sDs7zwqyZLTDu6P57CN5VFz4Yjc1emupFX5NFWor5jull9cr+ilOmfnBSCQPV0ArKrpKjrL9K9NJAhRKOqxmpLKx3pozGnrQMFKM0xsSuTcOCdyTdZF8JEQESeENHzwyoB4=

install:
- go get -u golang.org/x/lint/golint
- git submodule update --init

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
- make testenv

script:
- diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
- diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
- go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- make release-cli

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rPHL3SyAvAu7pyL1g/PxLDqEOEkcHRIe5xX4Klc21vEpcNcLzokbmI/cTBnC/rBp55t55PFc+mF9KN5DdHWHD5u65ubikytbF3Oo3/HS+Sg/My9M3Z+RpxVF2rOe7dI6Gg3FpjC2m5m0LdhbiBMtyt1oFsWA759RU/cW3vXXMmeRjBn8J12ol1++dHeNEtIWem0f8oebrZ453R5tN5rjhKTN/po4KnfEmPDDdUU41jZVjXxzx7Y0w/OvkJEV49QjQ429WudWM4XyCn3XOCv7R3diOGzbxxBdiBQPo5es+R167NYP1FJdMi5OLbPekwK0ZCT+3woVDUCKxMSj6jMo6zkiza9DQljiZxmt6F7Si9IMrrTVXgqYAHve3HXfrvKg3f7rAGj/fV3NLn6qz9luwGrwkiu7QRHHyC+HQKZPLL0UqLoLsR8IU+1I6163rYItC6IaaIYn3gQcr4aIlpO3BDoZBp4nA3SVKEnTxnFOQh71mrFY1Ym+U4G0bUBjX+lWw+VGgiQ5v2ebt2UFD9MKk4D6DW05E2LkfAYEnq7orALD/5iVYrqLR0csLoxsiAy7SciKWmSHLVHqUK4CGskBxqkIVu117w8EhV1oG0DmjNb8XRsb0HtdU2NIxlJLOf4p0Y1WKLuNMOiZT0hEcfHf5c6KCef4bekozNIvMdNyTuI=
  file_glob: true
  file: release/temporal-*
  on:
    tags: true
    repo: RTradeLtd/Temporal

notifications:
  email: false
