language: go
go:
- '1.12'
services:
- docker
sudo: required
env:
  matrix:
    - SSL_MODE_DISABLE=true
  global:
    - GO111MODULE=on
    # decodes into SENGRID_API_KEY environment variable
    - secure: GXKJ+1Wa+pqUm1PKHJMbDrejSfIsqhsZ6l88i0paTvVou9T/mv03mx9hzrSLsYXFFVjinfbKysxMtEorTFDl0YBSNxuPc7eaiJinnoptubBh++bvEzF/A8wmWHgIBxroFIrK4SNsnreCXPqT1YBQZWi3JenMkzS68j1oa/uPa5ODZ3rjx1Wmu6hSANSZPqzOoGO6lnRP8G30oiFzbawEnB/52iBcHhPtffUihLFnn3k1wXyL8fpi4JYuyNQe84Br+w91KSS2nMmG+RVvJWumHNGXFyjEVv0n7HbirjCBI1iZo50bTdFtujkGSOCoHqM1hwa2yLWISipkb19Ls4eeWcWZBFpcdBhIIeHEmz9iCXxn0ksIGzuw00Xof/HTcWUpnzzQFq4E8iVE4tmMrFbYEcD5vcGB3S7bURjTD38uZ3/7I4Oyuo33/WQGdDNIzugU/dycGkSNzwTeIB3yJfpr/wbC6lU5RnADh5Ej5hGreAfkng/iuC9T36Fnn9u4fTocj++smOxZSjbbKsyekNNdadYmU0sfd6Ka9mFcv8H6sDs7zwqyZLTDu6P57CN5VFz4Yjc1emupFX5NFWor5jull9cr+ilOmfnBSCQPV0ArKrpKjrL9K9NJAhRKOqxmpLKx3pozGnrQMFKM0xsSuTcOCdyTdZF8JEQESeENHzwyoB4=

install:
- go get -u golang.org/x/lint/golint
- git submodule update --init
- go mod download
- ( cd testenv ; go mod download )

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
- make testenv

script:
- diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
- diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
- go test -short -coverprofile=coverage.txt ./...
# - go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- make release-cli

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TolwpNbFdExKClWxbYYFXpOyksNfleeQs1g+VNxlQx1OocYDAGwmbyA2z8ZM78TXgOFcDsaEt0keuEtLxm41ZlznixQzMjQEIndxB5JFvJzMuHd5dC9e2EAx667d0QTfjzip/5iB4ZaKuX+JZS6el3OikgE30NrLgA5vH6mvYwO2KavoTZqBtdkvX08sI72tbjBCvdYy6jSpI6uJNGXk8aRgMDjMS0/QjKFnt2JuZb/0oVgJaBWrcquCYECsqOGmwHcdgdEdVKEftUwvnDtaiEf/DUXOmNgk2dsgeB+m7aex7ECPi90xBE7S6Ic7KmvH4LO9kfdLdKGUn68dFSMq1S2rMFd+fS7w0aZmcuXnIPfM5/8gswB8Y5dtLjpuZ1Usj3YgB9SGWqPu2glAuh04RRvKXChZmqe66H7eEJE8OTucRep/XpYCEu18Y7Jh6sdegEXUszX65puEUGh7wyiUYhkqWpfZvdO1sB0TzsQRKvnMwJRoGsNAg/bP+H+gdPmn/r1uGfnqpTWYYl5C6MxKhC0O+JXso2n7QQDk3mPLDaGKlbdAVX4zaW5vPeOTwXrrhU6fdHwqreNsV+ZBKkCKGOqs9565DL7TGS72Vpa377szkdJcQ2XsFNIV29h8dx8mhYD+mMCCJV3AMk5NDakuPXyFip9FhRvJKrJKN7N3bLE=
  file_glob: true
  file: release/temporal-*
  on:
    tags: true
    repo: RTradeLtd/Temporal

notifications:
  email: false
