language: go
go:
- '1.11'
services:
- docker
sudo: required
env:
  - SSL_MODE_DISABLE=true
  # decodes into SENGRID_API_KEY environment variable
  - secure: GXKJ+1Wa+pqUm1PKHJMbDrejSfIsqhsZ6l88i0paTvVou9T/mv03mx9hzrSLsYXFFVjinfbKysxMtEorTFDl0YBSNxuPc7eaiJinnoptubBh++bvEzF/A8wmWHgIBxroFIrK4SNsnreCXPqT1YBQZWi3JenMkzS68j1oa/uPa5ODZ3rjx1Wmu6hSANSZPqzOoGO6lnRP8G30oiFzbawEnB/52iBcHhPtffUihLFnn3k1wXyL8fpi4JYuyNQe84Br+w91KSS2nMmG+RVvJWumHNGXFyjEVv0n7HbirjCBI1iZo50bTdFtujkGSOCoHqM1hwa2yLWISipkb19Ls4eeWcWZBFpcdBhIIeHEmz9iCXxn0ksIGzuw00Xof/HTcWUpnzzQFq4E8iVE4tmMrFbYEcD5vcGB3S7bURjTD38uZ3/7I4Oyuo33/WQGdDNIzugU/dycGkSNzwTeIB3yJfpr/wbC6lU5RnADh5Ej5hGreAfkng/iuC9T36Fnn9u4fTocj++smOxZSjbbKsyekNNdadYmU0sfd6Ka9mFcv8H6sDs7zwqyZLTDu6P57CN5VFz4Yjc1emupFX5NFWor5jull9cr+ilOmfnBSCQPV0ArKrpKjrL9K9NJAhRKOqxmpLKx3pozGnrQMFKM0xsSuTcOCdyTdZF8JEQESeENHzwyoB4=

install:
- go get -u golang.org/x/lint/golint
- git submodule update --init

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
- make testenv

script:
- diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
- diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
- go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- make release-cli

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Xv0Zq+E638TZf0c3/tTUk/iizQ92hhW02cWUSnmGlBpWR8O5qvfcrgBYpohMIyFn42WEa/vJWT51aIfoZX779Xj41LodXx1QqnI/kQFHlVETeGXhsBbw8OsVAgKNtUII5XxrdyTe8h1JrFqCbynUgsBQK6t+ibTKYL4MTXwoJ3snGHiA7u0QVGWX4o3Q4axWqwJDVFFiSC1ekfRULgoINouAJcLVXvVp3VJOf7R8TZM9HgeSmiq+Vjm9eZ4hh3A3f312dO6T+duFhCBzU3aqktJYzJPxtQ5IcYc0Yr4rI1s2CKReT9qRdWjfSyQieCEDSS8miW3zChbdFGl1ntSJypOCh923jeAOMWDrichDB5icQNL/svpE128TxwEJt70MAK/0AFF/1t676kuEskEbTwFGBTmKW8y1F2AejwsnkxfUpKrzabkVDksLt0kqXBEPkrdCeCQ+/WvjPIHarO+zi6J7Qn38PaZBR7P/ssghvDjusZA1zm2ZoffvB5O0KGQ64fivcCeCuONGlouFXX/77NnmvYY8ua6QKLIkq3QnwOeGZNeCFWAQWd9rn2KM64K6AvoyIHRuBFB+FtIrZKHj9N2iVytnnqOvfnfySQg6ieiRuKJMjDnLQDoQdhuW0KJmaxOCMpNiE95Pj1GsepfMZe04fXLSO4srIfnedRFk7/Q=
  file_glob: true
  file: release/temporal-*
  on:
    tags: true
    repo: RTradeLtd/Temporal

notifications:
  email: false
