language: go
go:
  - "1.11"
services:
  - docker

install:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -v
  - docker pull koalaman/shellcheck

before_script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/**/*.{sh,bash}
  - go vet ./...
  - go fmt ./...
  - go build
  - go test -run xxxx ./...

script:
  - go test -race -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false 
